  - name: Install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: Start and enable MySQL service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true

  - name: Copy the SQL file to the MySQL server
    ansible.builtin.copy:
      src: mysql.sql
      dest: /tmp/mysql.sql

  - name: Execute the SQL file to create database and user
    ansible.builtin.command: mysql_secure_installation --set-root-pass=ecom@20260606